LogCleanup:
  cleanup_enabled: true
  max_log_files: 10
  retention_days: 7
  retention_strategy: time
Logging:
  console_log_level: INFO
  enable_dynamic_log_level: true
  log_dir: logs/push_to_talk_logs
  log_format: json
  log_level: INFO
  log_to_console: false
audio_device_index: 2
channels: 1
documentation_file: README.md
dtype: float32
enable_noise_reduction: true
enable_system_monitoring: true
gui_settings:
  always_on_top: false
key_combination:
- ctrl
- alt
- space
key_listener_sleep: 0.1
max_recording_duration: 60
model_support:
  available_models:
  - tiny
  - base
  - small
  - medium
  - large
  default_model: medium
record_audio: true
samplerate: 16000
save_audio: false
save_directory: transcriptions
save_transcription: false
use_fp16: true
