BUFFER_MAX_DURATION: 120
LogCleanup:
  cleanup_enabled: true
  max_log_files: 10
  retention_days: 7
  retention_strategy: time
Logging:
  console_log_level: INFO
  log_dir: logs/push_to_logs
  log_level: DEBUG
  log_to_console: false
channels: 1
documentation_file: README.md
dtype: float32
enable_system_monitoring: true
gui_settings:
  always_on_top: true
key_combination:
- ctrl
- shift
- space
key_combination_config:
  configurable_via_gui: true
key_listener_sleep: 0.1
model_support:
  available_models:
  - tiny
  - base
  - small
  - medium
  - large
  default_model: base
progress_bar_enabled: true
record_audio: true
recording_timeout: 60
samplerate: 16000
save_directory: transcriptions
save_transcription: false
system_monitoring_interval: 60
use_fp16: false
