# --------------------- General Settings ---------------------
key_combination: ['ctrl', 'alt', 'space']   # Key combination to toggle recording
save_directory: 'transcriptions'            # Directory for saving transcriptions (not used anymore, but can be retained)
use_fp16: False                             # Use FP16 precision for faster inference, not recommended on unsupported GPUs

# --------------------- Model Support ---------------------
model_support:
  default_model: 'base'                     # Default Whisper model to use
  available_models: ['tiny', 'base', 'small', 'medium', 'large']  # Available Whisper models

# --------------------- Audio Settings ---------------------
samplerate: 16000                           # Audio sample rate for recording
channels: 1                                 # Number of audio channels
dtype: 'float32'                            # Data type for the audio input
buffer_max_duration: 120                    # Maximum buffer duration in seconds (though this may no longer apply)

# --------------------- GUI Settings ---------------------
gui_settings:
  always_on_top: True                       # Set the GUI window to always stay on top
  enable_dark_mode: True                    # Enable dark mode
  log_to_console: True                      # Enable logging output to console
  resizable: True                           # Allow the window to be resizable
  enable_waveform_display: True             # Enable real-time waveform display

# --------------------- System Monitoring Settings ---------------------
enable_system_monitoring: True              # Enable system performance monitoring
system_monitoring_interval: 60              # Interval in seconds to check system performance

# --------------------- Logging Settings ---------------------
Logging:
  log_level: 'INFO'                         # Logging level, can be 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
  log_dir: 'logs/push_to_logs'              # Directory where logs will be stored
  log_to_console: True                      # Enable logging to console
  console_log_level: 'INFO'                 # Log level for console logging

# --------------------- Log Cleanup Settings ---------------------
LogCleanup:
  cleanup_enabled: True                     # Enable log cleanup
  retention_strategy: 'time'                # Retention strategy: 'time' or 'size'
  retention_days: 7                         # Retain logs for 7 days
  max_log_files: 10                         # Retain up to 10 log files (if using size-based retention)

# --------------------- Progress Bar ---------------------
progress_bar_enabled: True                  # Enable progress bar during transcription

# --------------------- Language Support ---------------------
language: 'english'                         # Default language for transcription
